### ISSUE TITLE
Do you have sample code for using this package?!

### ISSUE THREAD

**Issue by dotku** [okgrow/meteor-dotenv#4]
I'm new to Node.js and Meteor. I got error as:

> Your application is crashing. Waiting for file change.

Here is my code

```
var dotenv = Meteor.require('dotenv');
dotenv.load();

Meteor.startup(function(){
  console.log(process.env.GOOGLE_API_KEY);
});
```

**Comment by pauldowman** [comment]
To install it just do `meteor add pauldowman:dotenv`. You don't need any require statement.
